var changelog_langEn = {
'issue-id-1' : '<li><del>#1 - CO2e calculation approximation with using round kilometers, better use meters.</del></li>',
'issue-id-2' : '<li><del>#2 - Map is not centered on global view when chaining trips.</del></li>',
'issue-id-3' : '<li><del>#3 - After trip deletion, GPS trace remains on the map.</del></li>',
'issue-id-4' : '<li><del>#4 - Backward button still use old URL on changelog page, that causes error on watermark over Leaflet map.</del></li>',
'issue-id-5' : '<li><del>#5 - "+" operator concats strings instead of summing numbers.</del></li>',
'issue-id-6' : '<li><del>#6 - Markers are not shown when using train.</del></li>',
'feature-id-1' : '<li><del>Dropdown list for Nominatim query results in order to let the user choose the desired location instead of using the only first result.</del></li>',
'feature-id-2' : '<li><i>Find better direction service for public transportation.</i></li>',
'feature-id-3' : '<li><i>Evaluate network payload performances to decide if hosting external ressources could be relevant.</i></li>',
'feature-id-4' : '<li><del>Coloring different trips on the map.</del></li>',
'feature-id-5' : '<li><i>Look for filtered list of POIs when using public transportations to ensure that steps are stop stations.</i></li>',
'v1.0.0-release_date' : 'Jan 28th, 2023',
'v1.0.0-release_notes' : '<li><strong>Original release</strong></li>',
'v1.1.0-release_date' : 'Fev 3rd, 2023',
'v1.1.0-release_notes' : '<li><strong>Multimodal management</strong> (plan itinerary with differents transportations) : it is now possible to chain multiple trips with different transportation</li> <li>Better responsive design and text alignment</li>',
'v1.2.0-release_date' : 'Fev 4th, 2023',
'v1.2.0-release_notes' : '<li><strong>Multimodal management :</strong> adding "delete" option</li> <li><strong>Easy step management :</strong> remove, invert list</li> <li>Using pretty buttons for step management</li>',
'v1.2.1-release_date' : 'Fev 4th, 2023',
'v1.2.1-release_notes' : '<li><strong>Bug fixes :</strong> resolving issues <strong>#1</strong> and <strong>#3</strong></li> <li>Using pretty button for step deletion in result sub-part</li>',
'v2.0.0-release_date' : 'Mar 8th , 2023',
'v2.0.0-release_notes' : '<li><strong>Adding plane support</strong> (distance estimated on a crowfly beetween steps)</li> <li><strong>Adding regular and high-speed train support</strong> (distance estimated on a crowfly beetween steps)</li>',
'v2.1.0-release_date' : 'Mar 21th, 2023',
'v2.1.0-release_notes' : '<li><strong>Regular and high-speed train trips now use BRouter.de</strong> (really sticks to the railway, enhancing precision in distance calculation)</li>',
'v2.2.0-release_date' : 'Apr 24th, 2023',
'v2.2.0-release_notes' : '<li><strong>Allow direct use of GPS coordinates</strong> (both DD and DMS format)</li> <li>Text correction</li>',
'v2.2.1-release_date' : 'Apr 29th, 2023',
'v2.2.1-release_notes' : '<li><strong>Adding multilanguage support</strong>',
'v2.2.2-release_date' : 'May 10th, 2023',
'v2.2.2-release_notes' : '<li>Adding <strong>watermark</strong> and <strong>screenshot and download button</strong> for LeafLet map</li>',
'v2.2.3-release_date' : 'May 15th, 2023',
'v2.2.3-release_notes' : '<li>Code cleaning and refactoring</li>',
'v2.2.4-release_date' : 'May 24th, 2023',
'v2.2.4-release_notes' : '<li><strong>Bug fixes :</strong> resolving issue <strong>#4</strong></li>',
'v2.3.0-release_date' : 'Jun 4th, 2023',
'v2.3.0-release_notes' : '<li><strong>Adding Openrouteservice autocomplete</strong> to allow user to choose pre-processed location based on provided text string</li>',
'v2.3.1-release_date' : 'Jun 10th, 2023',
'v2.3.1-release_notes' : '<li>Handling empty user input to prevent querying Openrouteservices in this case</li>',
'v2.3.2-release_date' : 'Jul 3rd, 2023',
'v2.3.2-release_notes' : '<li><strong>Bug fixes :</strong> resolving issue <strong>#5</strong></li> <li>Adding Openrouteservice fallback for unsuccessful Nominatim queries</li>',
'v2.4.0-release_date' : 'Jul 16th, 2023',
'v2.4.0-release_notes' : '<li><strong>Bug fixes :</strong> resolving issue <strong>#2</strong></li> <li><strong>Implementing feature "<i>Coloring different trips on the map</i>"</strong> and adding markers that allows to identify departure and arrival</li> <li><strong>Adding full screen button</strong> on Leaflet map</li>',
'v2.5.0-release_date' : 'Aug 1st, 2023',
'v2.5.0-release_notes' : '<li><strong>Adding POIs look up</strong> into 2km radius to choose the closest station to the provided location when using train. Made with <strong>Overpass API</strong>.</li> <li><strong>Bug fixes :</strong> resolving issue <strong>#6</strong></li>',
'v2.6.0-release_date' : 'Aug 5th, 2023',
'v2.6.0-release_notes' : '<li>Enhancing <strong>POIs look up</strong> to find nearest train station (up to 10km radius) and nearest airport (up to 100km radius) to the provided location when using train or plane, still using <strong>Overpass API</strong>.</li>',
'v2.6.1-release_date' : 'Sep 19th, 2023',
'v2.6.1-release_notes' : '<li><strong>Enhancing customization</strong> for instancies (map center, colors)</li> <li><strong>Pre-adding mobility alternatives button</strong> (shared, low CO2e).</li>',
}
var co2ecalculator_langEn = {
'manual' : 'Based on provided geolocations, here\'s the operation mode to provide an <u>estimated</u> CO2e emission for the specified trip : <ul> </br> <li>Each location string (than can be picked in an autocomplete dropdown list provided throught <strong>Openrouteservice</strong> Autocomplete API) is sent to <strong><a href="https://nominatim.openstreetmap.org/" target="_blank">Nominatim Openstreetmap</a></strong> to query the OSM database for [lat,lon] GPS coordinates then stored in a list.</li> <ul> <li> <i>If GPS coordinates are directly provided (whether DD : ex: 45.8994, 6.1269 or DMS format : ex: 45°53\'57.8"N 6°07\'36.8"E), the tools skips the location query on Nominatim.</i> </li> </ul> </br> <li>This [lat,lon] GPS coordinates list is sent over a different routing API based on chosen transportation mode : </li> <ul> <li> <strong><a href="https://openrouteservice.org/" target="_blank">OpenRouteService</a> directions API</strong> for any "road" mode, in order to plan a trip throught all these locations and obtain kilometers journey length and route as a GPS points array. </br> <i>Openrouteservice directions API only supports transportation profiles driving-car and regular-bike, so public transportations may required to specify steps to match with the local public transportation plan. This could be also be a future enhancement.</i> </li> <li> <strong>A simple crowfly</strong> math calculation for plane, this needs to declare as many steps as possible. Tool selects the nearest airport from the provided location by iterative radius search (up to 100km) into Openstreetmap data using <strong>Overpass API</strong>. </li> <li> <strong><a href="https://brouter.de/" target="_blank">BRouter.de</a></strong> for trains journey, that sticks as much as possible to railway path. Tool selects the nearest station from the provided location by iterative radius search (up to 10km) into Openstreetmap data using <strong>Overpass API</strong>. </li> </ul> </br> <li> Total kilometers is sent to <strong><a href="https://impactco2.fr/transport" target="_blank">Mon Impact Transport API</a></strong> (provided by ADEME, FR gov. ecologic transition agency), with chosen transportation mode. It returns kgco2e emissions, then divided by carpoolers if specified. </li> <ul> <li> <i>Default passengers number is 1 for any other transportation than car and electric car, as estimation returned from ADEME for buses assumes an average transportation occupancy.</i> </li> </ul> </br> <li> GPS points array is shown as a line over a <strong><a href="https://leafletjs.com/" target="_blank">Leaflet</a></strong> Map, centered to fit global itinerary within the tile. This is usefull to see if the tool actually match with expected or realized journey. </li> </ul> <div class="alert alert-dark" role="alert"> No data is stored on the server, all computation is done client-side by the web-browser. All is HTML5/Javascript written and prettified with Bootstrap 5 CSS library. Some functions (GPS coord. validation) have been AI-written using <strong><a href="https://chat.openai.com/" target="_blank">ChatGPT</a></strong> prompts. </div> All recensed bugs and futur features can be find on <a href="./changelog.html" class="link-dark">changelog page</a>.',
}
